### ISSUE TITLE
failing to Build usb_mic_recorder on latest ESP-IDF (AIS-1872)

### ISSUE THREAD

**Issue by shvmm** [espressif/esp-skainet#152]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

A Clean compile without error.

### Actual behavior (suspected bug)

It was compiling fine with previous ESP-IDF ver. 5.3.2

### Error logs or terminal output

```shell
D:/Desktop/esp-proj/ESP-IDF/esp-skainet/components/hardware_driver/boards/esp32s3-eye/bsp_board.c: In function 'bsp_get_feed_data':
D:/Desktop/esp-proj/ESP-IDF/esp-skainet/components/hardware_driver/boards/esp32s3-eye/bsp_board.c:110:25: error: initialization of 'int32_t *' {aka 'long int *'} from incompatible pointer type 'int16_t *' {aka 'short int *'} -Wincompatible-pointer-types]
  110 |     int32_t *tmp_buff = buffer;
      |                         ^~~~~~
```

### Steps to reproduce the behavior

1. Open the project in ESP-IDF
2. Set SDK Config options:
3. Audio Media HAL > Audio hardware board: ESP32-S3-EYE
4. Run Build Project.

### Project release version

latest

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Windows

### Operating system version

Windows 11

### Shell

PowerShell

**Comment by sun-xiangyu** [comment]
Thanks for your feedback. It has been fixed.

**Comment by shvmm** [comment]
Sorry, still not fixed
```
D:/Desktop/esp-proj/ESP-IDF/esp-skainet/components/hardware_driver/boards/esp32s3-eye/bsp_board.c: In function 'bsp_get_feed_data':
D:/Desktop/esp-proj/ESP-IDF/esp-skainet/components/hardware_driver/boards/esp32s3-eye/bsp_board.c:110:25: error: initialization of 'int32_t *' {aka 'long int *'} from incompatible pointer type 'int16_t *' {aka 'short int *'} [-Wincompatible-pointer-types]
  110 |     int32_t *tmp_buff = buffer;
      |                         ^~~~~~
```

**Comment by Jefke1** [comment]
Hi Eric,
Same error.
esp-skainet/components/hardware_driver/boards/esp32s3-devkit-c/bsp_board.c:110:25: error: initialization of 'int32_t *' {aka 'long int *'} from incompatible pointer type 'int16_t *' {aka 'short int *'} [-Wincompatible-pointer-types]
  110 |     int32_t *tmp_buff = buffer;

int32_t changed to int16_t then it compiles but i can't get it to work. Everything looks fine but no response afther wake word hi esp.

**Comment by Gangwa-Labs** [comment]
Still facing this issue on esp-idf 5.5.1 ESP32-S3-EYE testing with wake word
error: initialization of 'int32_t *' {aka 'long int *'} from incompatible pointer type 'int16_t *' {aka 'short int *'} [-Wincompatible-pointer-types]
  110 |     int32_t *tmp_buff = buffer;

if you change int32_t -> int16_t it will compile but doesn't wake to the wake word

**Comment by MuhammadHassan5719** [comment]
esp-skainet/components/hardware_driver/boards/esp32s3-devkit-c/bsp_board.c:110:25: error: initialization of 'int32_t *' 
{aka 'long int *'} from incompatible pointer type 'int16_t *' {aka 'short int *'} [-Wincompatible-pointer-types]
  110 |     int32_t *tmp_buff = buffer;

having this issue with ESP32-S3-DevKitC-1
